# Generated by Django 5.0.6 on 2024-07-16 04:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p1backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='point_geom',
            field=django.contrib.gis.db.models.fields.PointField(db_column='wkb_geometry', srid=4326),
        ),
        migrations.AlterModelTable(
            name='city',
            table='Cities_India',
        ),
    ]
